version: '3'

services:
  neo4j:
    image: neo4j:latest
    network_mode: "bridge"
    environment:
      NEO4J_AUTH: 'neo4j/123'
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
    volumes:
      - neo4j:/data:/data
      - neo4j:/logs:/logs
      - neo4j:/import:/var/lib/neo4j/import
      - neo4j:/plugins:/plugins
volumes:
  neo4j:
